export interface Restaurant {
    id: string;
    name_en: string;
    name_ar: string;
    name_fr: string;
    picture: string;
    email: string;
    phone: string;
    address: string;
    description_en: string;
    description_ar: string;
    description_fr: string;
    max_delivery_distance: number;
    price_per_km: number;
    longitude: number;
    latitude: number;
    country: string;
    state: string;
    city: string;
    postal_code: string;
    is_pickup: boolean;
    is_delivery: boolean;
    use_wallet_balance: boolean;
    show_on_homepage: boolean;
    restaurant_rating: number;
    restaurant_rating_count: number;
    allow_scheduled_delivery: boolean;
    max_advance_schedule_days: number;
    sales_tax: number;
    service_fee: number;
    pickup_contractual_commission: number;
    delivery_contractual_commission: number;
    credit_card_fee: number;
    preparation_time: string;
    preparation_time_from: number;
    preparation_time_to: number;
    estimation_per_order: number;
    owner_id: string;
    is_branch: boolean;
    parent_restaurant_id: string | null;
    parent_restaurant: any;
    fee_service_percentage: boolean;
    sale_tax_percentage: boolean;
    pcc_percentage: boolean;
    dcc_percentage: boolean;
    ccf_percentage: boolean;
    cashback_percentage: number;
    status: string;
    online_status: string;
    offline_for: number;
    banner_url: string | null;
    open_days: Array<{
      id: string;
      day: string;
      opening_time: string;
      closing_time: string;
      restaurant_id: string;
      is_open: boolean;
      deleted_at: string | null;
    }>;
    payment_methods: Array<{
      id: string;
      restaurant_id: string;
      restaurant: any;
      payment_method_id: string;
      payment_method: {
        id: string;
        method_name: string;
        status: string;
        description: string;
      };
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
    }>;
    restaurant_specialities: Array<{
      id: string;
      restaurant_id: string;
      restaurant: any;
      category_id: string;
      category: any;
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
    }>;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
  }